#!/usr/bin/env python3

# (c) 2020 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# released under GPLv2
# use at your own risk

# This script can be used as a daily cronjob
# that updates ipsets with the DROP data from Spamhaus
# to be used in iptables firewalls

from pyroute2.ipset import IPSet
from socket import (AF_INET, AF_INET6)
import requests

spamhaus = {AF_INET6: { 'url': ['https://www.spamhaus.org/drop/dropv6.txt'],
                        'ipset': 'spamhaus_inet6', },
            AF_INET : { 'url': ['https://www.spamhaus.org/drop/drop.txt',
                                'https://www.spamhaus.org/drop/edrop.txt'],
                        'ipset': 'spamhaus_inet', },
           }

ipset = IPSet()

for family, info in spamhaus.items():

    nets = set()

    for url in info['url']:
        # print('Retrieving %s' % url)
        r = requests.get(url)
        if r.status_code == 200:
            for line in r.text.split('\n'):
                net = line.split(';')[0].strip()
                if net:
                     nets.add(net)
    if nets:
        # print('Flushing %s' % info['ipset'])
        ipset.flush(name=info['ipset'])

        for net in nets:
            # print('Adding %s' % net)
            ipset.add(name=info['ipset'], entry=net, etype='net', family=family)
